---
- name: Daemon reload
  command: systemctl daemon-reload
  become: yes
  listen: Restart docker
- name: Restart docker
  service:
    name: docker.service
    state: restarted
  become: yes
  listen: Restart docker

- name: Daemon reload
  command: systemctl daemon-reload
  become: yes
  listen: Restart journald
- name: Restart journald
  service:
    name: systemd-journald
    state: restarted
  become: yes
  listen: Restart journald

- name: Daemon reload
  command: systemctl daemon-reload
  become: yes
  listen: Restart sshd
- name: Restart sshd
  service:
    name: sshd
    state: restarted
  become: yes
  listen: Restart sshd

- name: Daemon reload
  command: systemctl daemon-reload
  become: yes
  listen: Reboot OS
- name: Reboot OS
  reboot:
  listen: Reboot OS
